import "./globals.css";
import PaymentsProvider from "../context/paymentsContext";

export const metadata = {
  title: "Payments UI",
  description: "Generated by Payments UI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><PaymentsProvider>{children}</PaymentsProvider></body>
    </html>
  );
}
